### PR TITLE
Use build args to fix building on macos

### PR DESCRIPTION
**Pull request by johanneswuerbach**
A different approach to resolved build issues on macos

Fixes https://github.com/DirectXMan12/k8s-prometheus-adapter/issues/198
Fixes https://github.com/DirectXMan12/k8s-prometheus-adapter/pull/231
Fixes https://github.com/DirectXMan12/k8s-prometheus-adapter/pull/244

### CODE REVIEW

**Comment by johanneswuerbach** [comment]
Do you have an example of what you had in mind? The make targets shouldn’t require any manual setting and work as before. Are there existing docs, which need updating?

**Comment by lilic** [comment]
The directory just needs to be created if it doesn't exist, at least for me locally.

**Comment by johanneswuerbach** [comment]
@lilic thanks, the output directory is created now if it doesn't exists.

**Comment by lilic** [comment]
Thanks! lgtm @s-urbaniak PTAL

**Comment by s-urbaniak** [comment]
lgtm :+1:

**Pull request merged**
