### PR TITLE
INCOMPLETE: External Metrics & deps

### PR DESCRIPTION
**Pull request by antoinne85**
First, let me start by saying that I'm not (yet) a golang developer, so some of this code may not be proper idiomatic go code and overall some of the approach might be incorrect.

This PR is 100% not even close to being ready to merge, but I wanted to go ahead and submit it to open up discussion on the topic and get some feedback early on before I spend a ton of time on it.

I'm aware that I didn't bring up the possibility of submitting a PR for issue #65 before submitting this, so I won't be offended if your not interested in my working on it.

So, without further ado, here's what you'll find below:
* I set up project dependencies using `dep`. Currently the only dependency listed is for the http://github.com/kubernetes-incubator/custom-metrics-apiserver project, which you've already updated to include boilerplate for External Metrics.
* I updated the code, as necessary, to correct any build errors related to the movement of several of the types out of the `apimachinery` namespace and into the `metrics` namespace.
* I updated the return type on `NewPrometheusProvider` to return the new `CustomMetricsProvider` interface (the old interface no longer exists in the boilerplate).
* I've renamed the `prometheusProvider` type to `customPrometheusProvider` provider to distinguish it from the newly created `externalPrometheusProvider`.
* I created an `externalPrometheusProvider` to implement the `ExternalMetricsProvider` interface.
* I stubbed out some rudimentary work in the `externalPrometheusProvider` type littered with incomplete work and `//TODO`s.

If you have the time, I'm interested in hearing your feedback on the work so far before I apply too much more time to it.

### Additional Notes
I was having a lot of difficulty building the project "out-of-the-box" due to type confusion issues around vendored dependencies. It seemed like no matter what I did I couldn't squash them all. Switching to `dep` trivialized all of that and got me up and running.

As a funny aside--the project is using `glide`.
Glide suggests using `godeps` instead.
Godeps suggests using `dep`.
So that's how I wound up with `dep`.

Cheers!

### CODE REVIEW

**Comment by antoinne85** [comment]
Oh--I should add this:
I didn't make any updates to the `Makefile` or `.travis.yml` files.

I've been building by executing:
`dep ensure`
`go build ./pkg/custom-provider`

(I'm working on Windows, so there are some hoops I'll need to jump through to be able to use the `Makefile` that I haven't jumped through yet.)

**Comment by DirectXMan12** [comment]
Hi!  Thanks for this work!  I've just merged a non-trivial refactor.  One of the things that it does is update the dependencies to Kubernetes 1.11 and switch over to `dep` :-).  If you can rebase your work on top of the latest master, I'd be happy to review it, and eventually merge.

**Comment by antoinne85** [comment]
I may have to scrap this and start over.
I've irreversibly ruined this branch from the looks of things.

**Comment by antoinne85** [comment]
I've created PR #79 to replace this one.
It's much cleaner.

**Pull request closed without merging**
