### PR TITLE
Ability to filter metrics according to labels provided

### PR DESCRIPTION
**Pull request by sergii-koshel-exa**
As [custom-metrics-apiserver](https://github.com/kubernetes-incubator/custom-metrics-apiserver) supports metrics selection using additional labels it is possible to support them here as well.

Using latest `custom-metrics-apiserver` requires to bump version for the following modules:
- `k8s.io/apimachinery` to `release-1.15`
- `k8s.io/apiserver` to `release-1.15`
- `k8s.io/client-go` to `release-12.0`
- `k8s.io/metrics` to `release-1.15`

`HPA` as below results in metrics matching `label1="value1"`:
```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaler-name
  namespace: <namespace-here>
spec:
 ...
  metrics:
  - type: Object
    object:
      target:
        kind: <object Kind>
        name: <object-name>
      selector:
        matchLabels:
          label1: value1
  ...
```

Fixes https://github.com/DirectXMan12/k8s-prometheus-adapter/issues/1

### CODE REVIEW

**Comment by mentos1386** [comment]
Hey @sergii-koshel-exa, this looks like an awesome feature. Is it still being worked on?

**Comment by sergii-koshel-exa** [comment]
It is done. Waiting for someone to look into

**Comment by mentos1386** [comment]
@s-urbaniak Sorry to bother you, but could you take a look at this?

**Comment by s-urbaniak** [comment]
@mentos1386 indeed, sorry for the delay, reviewing now.

**Comment by s-urbaniak** [comment]
@mentos1386 generally, lgtm :+1: thanks a lot! :tada: question: what version of Go did you use to bump the dependencies? Was it Go 1.13? If so, do you mind to bump `.travis.yml` too?

**Comment by sergii-koshel-exa** [comment]
Done.

**Comment by s-urbaniak** [comment]
great, thank you :+1: just one little extra request, as we are green: do you mind to introduce a separate commit for the code changes vs. the vendoring? thanks!

**Comment by sergii-koshel-exa** [comment]
I'm not sure I following what do you mean

**Comment by s-urbaniak** [comment]
you made changes in `pkg/custom-provider`. I am asking to have those changes in its own commit and the vendored changes in another commit :-)

**Comment by sergii-koshel-exa** [comment]
Enjoy!

**Comment by s-urbaniak** [comment]
lgtm, thanks a lot for the contribution! this is worth a new release :-)

**Comment by JulesBelveze** [comment]
Hey there,
As suggested by @sergii-koshel-exa I'm trying to use a `selector` inside my HPA, as follow:
```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: classifier-scaler
  namespace: dcgm-exporter
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: classifier
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: Object
    object:
      target:
        kind: Service
       selector:
         matchLabels:
           node_label: v100-pool
      target:
        type: Value
        averageValue: 70
```
but I get the following error:
```
the HPA was unable to compute the replica count: unable to get metric DCGM_FI_DEV_GPU_UTIL: Service on dcgm-exporter dcgm-exporter/unable to fetch metrics from custom metrics API: the server could not find the metric DCGM_FI_DEV_GPU_UTIL for services dcgm-exporter
```
I've checked on the Prometheus UI and `node_label` is available. Also query the metric within the HPA without the `selector` works well..

Any suggestion on how to fix this?
Cheers

**Pull request merged**
